name: flutter_license_manager
description: A comprehensive Flutter package for managing and displaying OSS license information with support for custom licenses and improved UI components.
version: 2.0.0
homepage: https://github.com/kihyun1998/flutter_license_manager
repository: https://github.com/kihyun1998/flutter_license_manager
issue_tracker: https://github.com/kihyun1998/flutter_license_manager/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - license
  - oss
  - open-source
  - legal
  - compliance